// apps/chat-widget/src/components/ui/image-modal.tsx
import { signal } from '@preact/signals';
import { clsx } from 'clsx';
import { ChevronLeft, ChevronRight, X } from 'lucide-preact';
import { useEffect } from 'preact/hooks';

// Global state for modal
export const imageModalState = signal<{
  isOpen: boolean;
  images: string[];
  currentIndex: number;
} | null>(null);

export function openImageModal(images: string[], index = 0) {
  imageModalState.value = { isOpen: true, images, currentIndex: index };
}

export function closeImageModal() {
  imageModalState.value = null;
}

export function ImageModal() {
  const state = imageModalState.value;

  useEffect(() => {
    if (!state?.isOpen) return;

    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') closeImageModal();
      if (e.key === 'ArrowLeft') navigatePrev();
      if (e.key === 'ArrowRight') navigateNext();
    };

    document.addEventListener('keydown', handleKeyDown);
    return () => document.removeEventListener('keydown', handleKeyDown);
  }, [state?.isOpen]);

  if (!state?.isOpen) return null;

  const { images, currentIndex } = state;
  const hasMultiple = images.length > 1;

  const navigatePrev = () => {
    if (!state) return;
    const newIndex = currentIndex > 0 ? currentIndex - 1 : images.length - 1;
    imageModalState.value = { ...state, currentIndex: newIndex };
  };

  const navigateNext = () => {
    if (!state) return;
    const newIndex = currentIndex < images.length - 1 ? currentIndex + 1 : 0;
    imageModalState.value = { ...state, currentIndex: newIndex };
  };

  return (
    <div
      className="chat-fixed chat-inset-0 chat-z-[100] chat-flex chat-items-center chat-justify-center chat-bg-black/90 chat-backdrop-blur-sm"
      onClick={closeImageModal}
    >
      {/* Close button */}
      <button
        onClick={closeImageModal}
        className="chat-absolute chat-top-4 chat-right-4 chat-p-2 chat-rounded-full chat-bg-white/10 hover:chat-bg-white/20 chat-text-white chat-transition-colors"
      >
        <X size={24} />
      </button>

      {/* Navigation - Previous */}
      {hasMultiple && (
        <button
          onClick={(e) => {
            e.stopPropagation();
            navigatePrev();
          }}
          className="chat-absolute chat-left-4 chat-p-3 chat-rounded-full chat-bg-white/10 hover:chat-bg-white/20 chat-text-white chat-transition-colors"
        >
          <ChevronLeft size={32} />
        </button>
      )}

      {/* Image */}
      <img
        src={images[currentIndex]}
        alt={`Image ${currentIndex + 1}`}
        className="chat-max-w-[90vw] chat-max-h-[85vh] chat-object-contain chat-rounded-lg chat-shadow-2xl"
        onClick={(e) => e.stopPropagation()}
      />

      {/* Navigation - Next */}
      {hasMultiple && (
        <button
          onClick={(e) => {
            e.stopPropagation();
            navigateNext();
          }}
          className="chat-absolute chat-right-4 chat-p-3 chat-rounded-full chat-bg-white/10 hover:chat-bg-white/20 chat-text-white chat-transition-colors"
        >
          <ChevronRight size={32} />
        </button>
      )}

      {/* Indicators */}
      {hasMultiple && (
        <div className="chat-absolute chat-bottom-6 chat-flex chat-gap-2">
          {images.map((_, idx) => (
            <button
              key={idx}
              onClick={(e) => {
                e.stopPropagation();
                if (state) {
                  imageModalState.value = { ...state, currentIndex: idx };
                }
              }}
              className={clsx(
                'chat-w-2.5 chat-h-2.5 chat-rounded-full chat-transition-all',
                idx === currentIndex
                  ? 'chat-bg-white chat-scale-110'
                  : 'chat-bg-white/40 hover:chat-bg-white/60'
              )}
            />
          ))}
        </div>
      )}

      {/* Counter */}
      {hasMultiple && (
        <div className="chat-absolute chat-top-4 chat-left-4 chat-px-3 chat-py-1 chat-rounded-full chat-bg-black/50 chat-text-white chat-text-sm chat-font-medium">
          {currentIndex + 1} / {images.length}
        </div>
      )}
    </div>
  );
}

// apps/portfolio/src/lib/components/ui/ImageModal.svelte
<script lang="ts">
	import { fade, scale } from 'svelte/transition';
	import { X } from 'lucide-svelte';

	export let src: string = '';
	export let alt: string = '';
	export let isOpen: boolean = false;

	function close() {
		isOpen = false;
	}

	function handleKeydown(e: KeyboardEvent) {
		if (e.key === 'Escape') close();
	}
</script>

<svelte:window on:keydown={handleKeydown} />

{#if isOpen && src}
	<button
		type="button"
		class="fixed inset-0 z-50 flex items-center justify-center bg-black/85 p-4 backdrop-blur-md cursor-zoom-out border-0 w-full h-full text-left"
		transition:fade={{ duration: 200 }}
		on:click={close}
	>
		<!-- Modal Content Box -->
		<div
			class="relative flex max-h-[90vh] max-w-[90vw] flex-col items-center justify-center overflow-hidden rounded-xl border border-white/10 bg-neutral-900/90 p-2 shadow-2xl cursor-default"
			transition:scale={{ duration: 250, start: 0.92 }}
			on:click|stopPropagation
			on:keydown|stopPropagation
			role="dialog"
			aria-modal="true"
		>
			<button
				type="button"
				on:click={close}
				class="absolute right-3 top-3 z-10 flex size-9 items-center justify-center rounded-full bg-black/60 text-white/80 transition-all hover:bg-black hover:text-white"
				aria-label="Close image preview"
			>
				<X class="size-5" />
			</button>

			<img
				{src}
				{alt}
				class="max-h-[82vh] max-w-[88vw] rounded-lg object-contain"
			/>
			{#if alt}
				<p class="mt-2 text-center text-xs font-medium text-white/75">{alt}</p>
			{/if}
		</div>
	</button>
{/if}
